import './globals.css'
import Header from '../components/Header'
import Sidebar from '@/components/Sidebar'
import { Providers } from '@/context/providers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <>
            <Sidebar />
            <div className="md:pl-64 flex flex-col">
              <Header />
              <main className="flex-1">
                {children}
              </main>
            </div>
          </>
        </Providers>
      </body>
    </html>
  )
}

